# Generated by Django 3.2 on 2023-09-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230903_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flat',
            new_name='flat',
        ),
    ]
