# Generated by Django 3.2 on 2023-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_owner_flat_owner_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='text_complaint',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='Новостройка'),
        ),
    ]
